/// Canonical feed data: GENERATED, identical in every app in this repo.
///
/// Generated by `bench/gen_items_v2.py`: the 13 clips the first comparison
/// measured, plus the four from DartNative's own playground feed demo that it
/// did not have. Every URL and poster is checked alive before it is written.
///
/// All apps consume this exact list, so any measured difference is the
/// framework, not the data.
library;

/// One video in the feed.
class VideoItem {
  final int id;
  final String url;
  final String poster;
  final String file;
  final int width;
  final int height;
  final int fps;
  final int duration;

  const VideoItem({
    required this.id,
    required this.url,
    required this.poster,
    required this.file,
    required this.width,
    required this.height,
    required this.fps,
    required this.duration,
  });

  double get aspectRatio => width / height;
}

/// Where the bytes come from. `network` streams the Pexels URL (the realistic
/// feed, and the configuration binary size is measured from). `local` plays a
/// bundled copy, removing network variance so the decode/render pipeline is
/// what's actually being timed.
const String kSource = String.fromEnvironment('SRC', defaultValue: 'network');
const bool kUseLocal = kSource == 'local';

/// Feed length. The list loops `index % demoItems.length`, so this reads as
/// infinite. 1000 is what the first comparison pinned both apps to, because
/// the hand-rolled `pagingEnabled` shim stopped snapping at 10000 rows. `0`
/// means no item count at all, for the apps whose pager supports it.
const int kFeedItemCount =
    int.fromEnvironment('FEED_COUNT', defaultValue: 1000);

/// `parity` is the first comparison's tuning, so a framework change is the
/// only variable. `upstream` is what DartNative's own feed demo now uses:
/// four live players on iOS, 2 MB pre-cached per page, one extra page
/// pre-cached past the pool window, and the fast-start buffering profile.
const String kTuning = String.fromEnvironment('TUNING', defaultValue: 'parity');

/// Pool + cache tuning, identical constants in every app.
class FeedTuning {
  static const bool upstream = kTuning == 'upstream';
  static const int preCacheBytes = upstream ? 2 * 1024 * 1024 : 500 * 1024;
  static const int preloadAhead = 2;
  static const int preCacheBeyond = upstream ? 1 : 0;
  static const int maxLiveControllers = upstream ? 4 : 3;
  static const int maxDiskCacheBytes = 100 * 1024 * 1024;
  static const Duration disposeSettle = Duration(milliseconds: 250);
}

/// The feed: 13 v1 clips, then the four upstream-only ones.
const List<VideoItem> demoItems = [
  VideoItem(
    id: 1526909,
    url: 'https://videos.pexels.com/video-files/1526909/1526909-hd_1280_720_24fps.mp4',
    poster: 'https://images.pexels.com/videos/1526909/pictures/preview-0.jpg',
    file: '1526909-hd_1280_720_24fps.mp4',
    width: 1280, height: 720, fps: 24, duration: 10,
  ),
  VideoItem(
    id: 1409899,
    url: 'https://videos.pexels.com/video-files/1409899/1409899-hd_1280_720_25fps.mp4',
    poster: 'https://images.pexels.com/videos/1409899/pictures/preview-0.jpg',
    file: '1409899-hd_1280_720_25fps.mp4',
    width: 1280, height: 720, fps: 25, duration: 21,
  ),
  VideoItem(
    id: 857251,
    url: 'https://videos.pexels.com/video-files/857251/857251-hd_1080_720_25fps.mp4',
    poster: 'https://images.pexels.com/videos/857251/pictures/preview-0.jpg',
    file: '857251-hd_1080_720_25fps.mp4',
    width: 1080, height: 720, fps: 25, duration: 14,
  ),
  VideoItem(
    id: 856973,
    url: 'https://videos.pexels.com/video-files/856973/856973-hd_1280_720_25fps.mp4',
    poster: 'https://images.pexels.com/videos/856973/pictures/preview-0.jpg',
    file: '856973-hd_1280_720_25fps.mp4',
    width: 1280, height: 720, fps: 25, duration: 14,
  ),
  VideoItem(
    id: 2169880,
    url: 'https://videos.pexels.com/video-files/2169880/2169880-hd_1280_720_30fps.mp4',
    poster: 'https://images.pexels.com/videos/2169880/pictures/preview-0.jpg',
    file: '2169880-hd_1280_720_30fps.mp4',
    width: 1280, height: 720, fps: 30, duration: 86,
  ),
  VideoItem(
    id: 3163534,
    url: 'https://videos.pexels.com/video-files/3163534/3163534-hd_1280_720_30fps.mp4',
    poster: 'https://images.pexels.com/videos/3163534/pictures/preview-0.jpg',
    file: '3163534-hd_1280_720_30fps.mp4',
    width: 1280, height: 720, fps: 30, duration: 30,
  ),
  VideoItem(
    id: 1093662,
    url: 'https://videos.pexels.com/video-files/1093662/1093662-hd_1280_720_30fps.mp4',
    poster: 'https://images.pexels.com/videos/1093662/pictures/preview-0.jpg',
    file: '1093662-hd_1280_720_30fps.mp4',
    width: 1280, height: 720, fps: 30, duration: 30,
  ),
  VideoItem(
    id: 5386411,
    url: 'https://videos.pexels.com/video-files/5386411/5386411-hd_1080_2048_25fps.mp4',
    poster: 'https://images.pexels.com/videos/5386411/pictures/preview-0.jpeg',
    file: '5386411-hd_1080_2048_25fps.mp4',
    width: 1080, height: 2048, fps: 25, duration: 15,
  ),
  VideoItem(
    id: 7438482,
    url: 'https://videos.pexels.com/video-files/7438482/7438482-hd_1080_1872_30fps.mp4',
    poster: 'https://images.pexels.com/videos/7438482/pictures/preview-0.jpeg',
    file: '7438482-hd_1080_1872_30fps.mp4',
    width: 1080, height: 1872, fps: 30, duration: 9,
  ),
  VideoItem(
    id: 5329239,
    url: 'https://videos.pexels.com/video-files/5329239/5329239-hd_1080_2048_25fps.mp4',
    poster: 'https://images.pexels.com/videos/5329239/pictures/preview-0.jpeg',
    file: '5329239-hd_1080_2048_25fps.mp4',
    width: 1080, height: 2048, fps: 25, duration: 64,
  ),
  VideoItem(
    id: 1526909,
    url: 'https://videos.pexels.com/video-files/1526909/1526909-hd_1920_1080_24fps.mp4',
    poster: 'https://images.pexels.com/videos/1526909/pictures/preview-0.jpg',
    file: '1526909-hd_1920_1080_24fps.mp4',
    width: 1920, height: 1080, fps: 24, duration: 10,
  ),
  VideoItem(
    id: 857251,
    url: 'https://videos.pexels.com/video-files/857251/857251-hd_1620_1080_25fps.mp4',
    poster: 'https://images.pexels.com/videos/857251/pictures/preview-0.jpg',
    file: '857251-hd_1620_1080_25fps.mp4',
    width: 1620, height: 1080, fps: 25, duration: 14,
  ),
  VideoItem(
    id: 1093667,
    url: 'https://videos.pexels.com/video-files/1093667/1093667-hd_1280_720_30fps.mp4',
    poster: 'https://images.pexels.com/videos/1093667/pictures/preview-0.jpg',
    file: '1093667-hd_1280_720_30fps.mp4',
    width: 1280, height: 720, fps: 30, duration: 13,
  ),
  VideoItem(
    id: 7197863,
    url: 'https://videos.pexels.com/video-files/7197863/7197863-hd_720_1280_25fps.mp4',
    poster: 'https://images.pexels.com/videos/7197863/pictures/preview-0.jpeg',
    file: '7197863-hd_720_1280_25fps.mp4',
    width: 720, height: 1280, fps: 25, duration: 14,
  ),
  VideoItem(
    id: 7150170,
    url: 'https://videos.pexels.com/video-files/7150170/7150170-sd_540_960_25fps.mp4',
    poster: 'https://images.pexels.com/videos/7150170/pictures/preview-0.jpeg',
    file: '7150170-sd_540_960_25fps.mp4',
    width: 540, height: 960, fps: 25, duration: 9,
  ),
  VideoItem(
    id: 6864993,
    url: 'https://videos.pexels.com/video-files/6864993/6864993-hd_720_1366_25fps.mp4',
    poster: 'https://images.pexels.com/videos/6864993/pictures/preview-0.jpeg',
    file: '6864993-hd_720_1366_25fps.mp4',
    width: 720, height: 1366, fps: 25, duration: 25,
  ),
  VideoItem(
    id: 12109326,
    url: 'https://videos.pexels.com/video-files/12109326/12109326-hd_720_1280_25fps.mp4',
    poster: 'https://images.pexels.com/videos/12109326/pictures/preview-0.jpeg',
    file: '12109326-hd_720_1280_25fps.mp4',
    width: 720, height: 1280, fps: 25, duration: 10,
  ),
];
