#!/usr/bin/env python3
"""Regenerate `feed_config.dart` for the September revisit, in all three apps.

v1 (`gen_items.py`) produced the 13-clip list the first post measured. This
adds the four clips DartNative's own playground feed demo uses that v1 did
not (`playground/lib/screens/media/video_feed_demo.dart`, 2026-09-17), so the
feed is the union of both: 17 clips. Every URL is checked with a ranged GET
before it is written; a dead URL would show up as an instant error rather
than a load and poison every TTFF number.

Writes byte-identical output to every app that reads it, so any measured
difference is the framework, not the data. Run from the repo root:

    python3 bench/gen_items_v2.py
"""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APPS = ['dartnative', 'dartnative-pageview', 'flutter']

# (id, file, poster file, width, height, fps, seconds)
V1 = [
    (1526909, '1526909-hd_1280_720_24fps.mp4', 'preview-0.jpg', 1280, 720, 24, 10),
    (1409899, '1409899-hd_1280_720_25fps.mp4', 'preview-0.jpg', 1280, 720, 25, 21),
    (857251, '857251-hd_1080_720_25fps.mp4', 'preview-0.jpg', 1080, 720, 25, 14),
    (856973, '856973-hd_1280_720_25fps.mp4', 'preview-0.jpg', 1280, 720, 25, 14),
    (2169880, '2169880-hd_1280_720_30fps.mp4', 'preview-0.jpg', 1280, 720, 30, 86),
    (3163534, '3163534-hd_1280_720_30fps.mp4', 'preview-0.jpg', 1280, 720, 30, 30),
    (1093662, '1093662-hd_1280_720_30fps.mp4', 'preview-0.jpg', 1280, 720, 30, 30),
    (5386411, '5386411-hd_1080_2048_25fps.mp4', 'preview-0.jpg', 1080, 2048, 25, 15),
    (7438482, '7438482-hd_1080_1872_30fps.mp4', 'preview-0.jpg', 1080, 1872, 30, 9),
    (5329239, '5329239-hd_1080_2048_25fps.mp4', 'preview-0.jpg', 1080, 2048, 25, 64),
    (1526909, '1526909-hd_1920_1080_24fps.mp4', 'preview-0.jpg', 1920, 1080, 24, 10),
    (857251, '857251-hd_1620_1080_25fps.mp4', 'preview-0.jpg', 1620, 1080, 25, 14),
    (1093667, '1093667-hd_1280_720_30fps.mp4', 'preview-0.jpg', 1280, 720, 30, 13),
]
# In the upstream demo and not in v1. The other seven upstream clips are
# already above.
UPSTREAM = [
    (7197863, '7197863-hd_720_1280_25fps.mp4', 'preview-0.jpeg', 720, 1280, 25, 14),
    (7150170, '7150170-sd_540_960_25fps.mp4', 'preview-0.jpeg', 540, 960, 25, 9),
    (6864993, '6864993-hd_720_1366_25fps.mp4', 'preview-0.jpeg', 720, 1366, 25, 25),
    (12109326, '12109326-hd_720_1280_25fps.mp4', 'preview-0.jpeg', 720, 1280, 25, 10),
]


def alive(url):
    code = subprocess.run(
        ['curl', '-s', '-o', '/dev/null', '-w', '%{http_code}', '-r', '0-1023',
         '-A', 'Mozilla/5.0', url],
        capture_output=True, text=True).stdout
    return code in ('200', '206')


items = []
for vid, file, poster, w, h, fps, secs in V1 + UPSTREAM:
    url = f'https://videos.pexels.com/video-files/{vid}/{file}'
    if not alive(url):
        sys.exit(f'dead video: {url}')
    # Pexels serves some posters as .jpg and some as .jpeg, and v1 had one
    # wrong (5386411 404s as .jpg), so take whichever answers.
    stem = poster.rsplit('.', 1)[0]
    purl = next((u for u in (
        f'https://images.pexels.com/videos/{vid}/pictures/{stem}.{ext}'
        for ext in ('jpg', 'jpeg')) if alive(u)), None)
    if purl is None:
        sys.exit(f'dead poster: {vid}')
    items.append((vid, url, purl, file, w, h, fps, secs))
print(f'{len(items)} alive items')

HEADER = '''/// Canonical feed data: GENERATED, identical in every app in this repo.
///
/// Generated by `bench/gen_items_v2.py`: the 13 clips the first comparison
/// measured, plus the four from DartNative's own playground feed demo that it
/// did not have. Every URL and poster is checked alive before it is written.
///
/// All apps consume this exact list, so any measured difference is the
/// framework, not the data.
library;

/// One video in the feed.
class VideoItem {
  final int id;
  final String url;
  final String poster;
  final String file;
  final int width;
  final int height;
  final int fps;
  final int duration;

  const VideoItem({
    required this.id,
    required this.url,
    required this.poster,
    required this.file,
    required this.width,
    required this.height,
    required this.fps,
    required this.duration,
  });

  double get aspectRatio => width / height;
}

/// Where the bytes come from. `network` streams the Pexels URL (the realistic
/// feed, and the configuration binary size is measured from). `local` plays a
/// bundled copy, removing network variance so the decode/render pipeline is
/// what's actually being timed.
const String kSource = String.fromEnvironment('SRC', defaultValue: 'network');
const bool kUseLocal = kSource == 'local';

/// Feed length. The list loops `index % demoItems.length`, so this reads as
/// infinite. 1000 is what the first comparison pinned both apps to, because
/// the hand-rolled `pagingEnabled` shim stopped snapping at 10000 rows. `0`
/// means no item count at all, for the apps whose pager supports it.
const int kFeedItemCount =
    int.fromEnvironment('FEED_COUNT', defaultValue: 1000);

/// `parity` is the first comparison's tuning, so a framework change is the
/// only variable. `upstream` is what DartNative's own feed demo now uses:
/// four live players on iOS, 2 MB pre-cached per page, one extra page
/// pre-cached past the pool window, and the fast-start buffering profile.
const String kTuning = String.fromEnvironment('TUNING', defaultValue: 'parity');

/// Pool + cache tuning, identical constants in every app.
class FeedTuning {
  static const bool upstream = kTuning == 'upstream';
  static const int preCacheBytes = upstream ? 2 * 1024 * 1024 : 500 * 1024;
  static const int preloadAhead = 2;
  static const int preCacheBeyond = upstream ? 1 : 0;
  static const int maxLiveControllers = upstream ? 4 : 3;
  static const int maxDiskCacheBytes = 100 * 1024 * 1024;
  static const Duration disposeSettle = Duration(milliseconds: 250);
}

/// The feed: 13 v1 clips, then the four upstream-only ones.
const List<VideoItem> demoItems = [
'''

body = ''.join(
    f"  VideoItem(\n    id: {vid},\n    url: '{url}',\n    poster: '{purl}',\n"
    f"    file: '{file}',\n    width: {w}, height: {h}, fps: {fps}, duration: {secs},\n  ),\n"
    for vid, url, purl, file, w, h, fps, secs in items)
out = HEADER + body + '];\n'

for app in APPS:
    p = ROOT / app / 'lib/feed_config.dart'
    p.write_text(out)
    print('wrote', p.relative_to(ROOT))

(ROOT / 'bench/items.txt').write_text('\n'.join(i[3] for i in items) + '\n')
