#!/usr/bin/env python3
"""Build the large hard-coded catalog for the full UI: up to 10,000 Pexels videos.

Uses the official Pexels API (a free key from https://www.pexels.com/api/).
pexels.com itself sits behind a bot challenge, and scraping around that is
not something this repo does. The key is read from the environment and never
written anywhere:

    PEXELS_API_KEY=... python3 bench/gen_catalog.py [count]

Portrait clips only, since the feed is full-screen vertical, collected across
several topics and de-duplicated by id. For each video the smallest file that
is at least 720 wide is chosen (else the largest under 1080), which is what a
phone feed should stream. Output: dartnative-pageview/lib/feed_catalog.dart.

The bench apps never read this file. Their shared 17-clip `feed_config.dart`
stays the like-for-like data set.
"""
import json
import os
import pathlib
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'dartnative-pageview/lib/feed_catalog.dart'
TARGET = int(sys.argv[1]) if len(sys.argv) > 1 else 10000
KEY = os.environ.get('PEXELS_API_KEY')
if not KEY:
    sys.exit('set PEXELS_API_KEY (free at https://www.pexels.com/api/)')

TOPICS = [
    'nature', 'city', 'ocean', 'people', 'travel', 'food', 'mountains', 'street',
    'night', 'rain', 'forest', 'beach', 'dance', 'sport', 'animals', 'sky',
    'fashion', 'music', 'car', 'coffee', 'snow', 'sunset', 'river', 'desert',
    'architecture', 'skate', 'surf', 'cooking', 'fitness', 'flowers', 'lights',
    'water', 'clouds', 'market', 'festival', 'cat', 'dog', 'bird', 'train', 'road',
]


def get(url):
    req = urllib.request.Request(url, headers={'Authorization': KEY, 'User-Agent': 'gen_catalog'})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                remaining = r.headers.get('X-Ratelimit-Remaining')
                return json.load(r), remaining
        except urllib.error.HTTPError as e:
            if e.code == 429:
                print('rate limited; waiting 60s', flush=True)
                time.sleep(60)
                continue
            if e.code >= 500:
                time.sleep(2 ** attempt)
                continue
            raise
    raise RuntimeError(f'gave up on {url}')


def pick_file(files):
    mp4 = [f for f in files if f.get('file_type') == 'video/mp4' and f.get('width') and f.get('link')]
    good = sorted((f for f in mp4 if 720 <= f['width'] <= 1080), key=lambda f: f['width'])
    if good:
        return good[0]
    small = sorted((f for f in mp4 if f['width'] <= 1080), key=lambda f: -f['width'])
    return small[0] if small else None


seen, items = set(), []
for topic in TOPICS:
    page = 1
    while len(items) < TARGET:
        data, remaining = get(
            f'https://api.pexels.com/videos/search?query={topic}'
            f'&orientation=portrait&per_page=80&page={page}')
        videos = data.get('videos', [])
        if not videos:
            break
        for v in videos:
            if v['id'] in seen:
                continue
            f = pick_file(v.get('video_files', []))
            if not f or not v.get('image'):
                continue
            seen.add(v['id'])
            items.append((v['id'], f['link'], v['image'], f['width'], f['height'],
                          round(f.get('fps') or 25), v.get('duration') or 0))
        print(f'{topic} p{page}: {len(items)} (quota left {remaining})', flush=True)
        if not data.get('next_page'):
            break
        page += 1
    if len(items) >= TARGET:
        break

items = items[:TARGET]
lines = [
    '/// GENERATED by `bench/gen_catalog.py` from the Pexels API: '
    f'{len(items)} portrait videos,',
    '/// hard-coded. Only the full UI reads this; the bench builds use the',
    '/// shared 17-clip `feed_config.dart`.',
    'library;',
    '',
    "import 'feed_config.dart';",
    '',
    'const List<VideoItem> catalogItems = [',
]
for vid, url, poster, w, h, fps, dur in items:
    file = url.rsplit('/', 1)[-1].split('?')[0]
    lines.append(
        f"  VideoItem(id: {vid}, url: '{url}', poster: '{poster}', file: '{file}', "
        f'width: {w}, height: {h}, fps: {fps}, duration: {dur}),')
lines.append('];')
OUT.write_text('\n'.join(lines) + '\n')
print(f'wrote {len(items)} videos to {OUT.relative_to(ROOT)}')
